# Defines the containers you want Docker Compose to run.
volumes:
  db_data:

networks:
  my-network:
    driver: bridge

services:
  db:
    image: mysql:8.0.42
    container_name: db
    restart: always
    env_file:
      - .env.db   # make it .env.db.example
    ports:
      - "3306:3306"   # host:container, change to 3307:3306 if you already have MySQL running locally
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/healthcheck.sh:/healthcheck.sh   # mount the script
    healthcheck:
      test: [ "CMD-SHELL", "/healthcheck.sh" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - my-network

  app:
    image: 428389801777.dkr.ecr.eu-west-1.amazonaws.com/library-manager:1.3
    container_name: app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.app    # make it .env.app.example
    ports:
      - "8080:8080"
    networks:
      - my-network
